name: Test Matrix Input Dependencies
run-name: test-matrix-inputs-${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      event_type:
        required: false
        default: argmax-sdk-swift-diarization,argmax-sdk-swift-realtime-asr,argmax-sdk-swift-prerecorded-asr

jobs:
  strategy:
    fail-fast: false
    matrix:
      event_type: ${{ fromJSON(format('[{0}]', inputs.event_type)) }}

  echo-event-type:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event type
        run: |
          echo "Event type: ${{ matrix.event_type }}"
