name: Test Matrix Input Dependencies
run-name: test-matrix-inputs-${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      event_type:
        required: false
        default: argmax-sdk-swift-diarization,argmax-sdk-swift-realtime-asr,argmax-sdk-swift-prerecorded-asr

jobs:
  echo-event-type:
    strategy:
      fail-fast: false
      matrix:
        event_type: ${{ inputs.event_type
          && fromJSON(format('["{0}"]', replace(replace(inputs.event_type, ' ', ''), ',', '","')))
          || fromJSON('["argmax-sdk-swift-diarization","argmax-sdk-swift-realtime-asr","argmax-sdk-swift-prerecorded-asr"]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo event type
        run: |
          echo "Event type: ${{ matrix.event_type }}"
